site_name: COCREATE UNIVERSITY
site_url: https://cocreate-asia.github.io/university/

nav:
  - Home: index.md
  - Git: git/index.md
  - Commit: git/commit.md
  
theme:
  name: material
  font: false

markdown_extensions:
  - admonition
  - footnotes
  - codehilite

plugins:
  - search
