site_name: COCREATE UNIVERSITY
nav:
    - Home: index.md
    - Git: git/index.md
theme:
    name: material
    font: false

markdown_extensions:
    - admonition
    - footnotes
    - codehilite

plugins:
    - search
